### ISSUE TITLE
memtest.efi isn't actually an efi file

### ISSUE THREAD

**Issue by nwmcsween** [martinwhitaker/pcmemtest#10]
Unbootable using uefi pxe or uefi ipxe, made via `cd build64; make`

**Comment by martinwhitaker** [comment]
I can boot the memtest.efi file using VirtualBox (with EFI enabled), qemu-system-x86_64 (using the OVMF firmware), the rEFInd boot manager, and directly from three separate UEFI BIOSs. So it quite definitely is a valid EFI file.

If you provide some details that let me reproduce your issue, I can look into why it isn't working for you.

**Comment by nwmcsween** [comment]
chain loading via ipxe gives:
`Could not boot: Exec format error (http://ipxe.org/2e008081)`
command ran is `chain http://boot/memtest/latest.efi` file exists and is available via wget and bit identical to build64 file. Chaining to what `file` identifies as PE based efi images works fine but not memtest.efi which `file` identifies as a Linux image.

**Comment by nwmcsween** [comment]
Also tried this under vmware esxi and pxe wouldn't accept the file but could possibly be a misconfiguration.
iPXE script to test this
````
#!ipxe
chain tftp://$server/memtest.efi
````

**Comment by martinwhitaker** [comment]
As noted in the README, the memtest.efi binary supports booting directly from a UEFI BIOS or indirectly using the various Linux boot protocols, i.e. it is a hybrid image. `file -k` reports the multiple identies:
````
% file -k memtest.efi
memtest.efi: Linux kernel x86 boot executable bzImage, version \353fHdrS\014\002, RW-rootFS,\012- DOS/MBR boot sector\012-  DOS/MBR boot sector\012-  PE32+ executable (EFI application) x86-64 (stripped to external PDB), for MS Windows\012- data
````
A Linux kernel built with the EFI stub loader enabled looks similar:
````
% file -k /boot/vmlinuz-5.10.60-desktop-2.mga8
/boot/vmlinuz-5.10.60-desktop-2.mga8: Linux kernel x86 boot executable bzImage, version 5.10.60-desktop-2.mga8 (iurt@ecosse.mageia.org) #1 SMP Wed Aug 18 11:12:31 UTC 2021, RO-rootFS, swap_dev 0x7, Normal VGA\012- DOS/MBR boot sector\012-  DOS/MBR boot sector\012-  PE32+ executable (EFI application) x86-64 (stripped to external PDB), for MS Windows\012- data
````
The GRUB `linux` command can successfully boot memtest.efi, so this is an ipxe compatibility issue.

Does ipxe work if you use the legacy-boot-only binary (memtest.bin)?

**Comment by martinwhitaker** [comment]
Using the iPXE implementation built into qemu (running on Mageia 8), I chain loaded memtest.efi served from a local http server without any problem. The iPXE configuration is:
````
iPXE 1.0.0+ (4bd064de) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP HTTPS iSCSI TFTP AoE ELF MBOOT PXE bzImage Menu PXEXT
````
The iPXE commands were
````
dhcp
chain http://192.168.0.1/memtest.efi
````

**Comment by nwmcsween** [comment]
This is very strange, only difference is I used rom-o-matic to generate a
ipxe image using the default settings and to pull from git, will open an
issue on ipxe and sorry for the noise

**Comment by martinwhitaker** [comment]
Assuming this is now resolved, so closing.
