### ISSUE TITLE
Can I user append parameters?

### ISSUE THREAD

**Issue by raddirad** [martinwhitaker/pcmemtest#12]
Hi

does the image (BIOS and EFI) get along with append parameters when loading pcmemtest?
e.g. I would like to turn off the machine once all RAM has been checked.

**Comment by martinwhitaker** [comment]
Currently the boot command line is ignored. If you wanted to change that, you would need to extend the definition of boot_params_t in boot/bootparams.h to include the cmd_line_ptr field and add code to parse the command line during startup.

**Comment by martinwhitaker** [comment]
Closing as answered.
