### ISSUE TITLE
please support ECC error polling

### ISSUE THREAD

**Issue by fezie** [martinwhitaker/pcmemtest#17]
Using version 1.5 from Debian experimental.
PCMemTest doenst't seem to support ECC error polling which would be useful.

I got correctable Errors from my ECC RAM under Linux, but PCMemTest reported after a full completed pass still 0 Errors.
And there doestn't seem to be anything about ECC error polling in the configuration menu.

After I rebooted in Linux I got another one, just after 6 Minutes:

```# edac-util -v
mc0: 0 Uncorrected Errors with no DIMM info
mc0: 0 Corrected Errors with no DIMM info
mc0: csrow2: 0 Uncorrected Errors
mc0: csrow2: mc#0csrow#2channel#0: 0 Corrected Errors
mc0: csrow2: mc#0csrow#2channel#1: 1 Corrected Errors
```

**Comment by martinwhitaker** [comment]
PCMemTest is now the basis for developing Memtest86+ v6.0. All future development will take place at https://github.com/memtest86plus/memtest86plus, so closing this issue. You can open an enhancement request there.
