### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by InfoLibre** [martinwhitaker/pcmemtest#18]
Could you post an ISO version? So users could use pcmemtest.

**Comment by InfoLibre** [comment]
Like here http://www.techguysg.com/posts/memorytest/

**Comment by JoshKeegan** [comment]
I wanted one too so built it (v1.5 release, 64 bit):
[memtest.zip](https://github.com/martinwhitaker/pcmemtest/files/8115551/memtest.zip)

Built with the following dockerfile:
```dockerfile
FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y build-essential make dosfstools mtools xorriso
```

**Comment by martinwhitaker** [comment]
PCMemTest is now the basis for developing Memtest86+ v6.0. All future development will take place at https://github.com/memtest86plus/memtest86plus, so closing this issue. I expect ISOs will be made available on www.memtest.org when v6.0 is released.
