### ISSUE TITLE
Build environment memory.h etc

### ISSUE THREAD

**Issue by vplk** [martinwhitaker/pcmemtest#19]
Hi,
I tried to build this with linux mint 20.3 64bit but first it was missing memory.h and did ln -s at pcmemtest/system for /usr/src/linux-headers-5.4.0-104-generic/include/config/memory.h 

then it started building but again for limits.h did etc. ln -s for /usr/include/linux/limits.h

but it goes errer later on.

How should I properly set build environment for this, any pointers would be apreceated. (btw. tnx for the work on really good tool have been using it for years :))

**Comment by martinwhitaker** [comment]
memory.h is my mistake - I always forget that it is an anachronism and we should use string.h instead. That's now fixed.

The only headers that should be used from the build system are limits.h, stdarg.h, stdbool.h, stddef.h, and stdint.h. These are all part of the C standard library and should be provided by and automatically found by GCC. I don't know why that isn't working on Linux Mint. You want the GCC version of limits.h, not the Linux one. On my system it is found in `/usr/lib/gcc/x86_64-mageia-linux-gnu/10/include/` - obviously that will be different for you.

**Comment by martinwhitaker** [comment]
PCMemTest is now the basis for developing Memtest86+ v6.0. All future development will take place at https://github.com/memtest86plus/memtest86plus, so closing this issue. You can open a new issue there if my changes did not fix the problem.
