### ISSUE TITLE
Keyboard is not powered on

### ISSUE THREAD

**Issue by doyanger** [martinwhitaker/pcmemtest#2]
A wonderful Memtest tool, easy to build and run on USB disk. 
but, USB Keyboard is not powered on when running this tool on Z490 mother board, (while it is on and work during BIOS stage, and get off when PCMemtest start run), so I can't control PCMemtest mannually.

**Comment by martinwhitaker** [comment]
Are you using UEFI or legacy boot? If UEFI, do you have the Compatibility Support Module (CSM) enabled in the BIOS.

**Comment by doyanger** [comment]
Hi @martinwhitaker 
I'm new to BIOS, I'll check these settings as you mentioned and update after chinese new year holiday, thank you very much!

**Comment by doyanger** [comment]
> Are you using UEFI or legacy boot? If UEFI, do you have the Compatibility Support Module (CSM) enabled in the BIOS.

UEFI boot mode. Enable CSM, It works!,  Thank you!

**Comment by doyanger** [comment]
Hi martinwhitaker, 
Excuse me, one more question.
how about some newer motherboards which have no CSM option and no legacy BISO boot mode.
thank you!

**Comment by doyanger** [comment]
Hi martinwhitaker
Excuse me, one more question,
how this program run on those newer motherboard which have no CSM option and only UEFI boot mode?

**Comment by martinwhitaker** [comment]
As said in the README, the memory test will run using the default configuration.

One day I hope to find the time to write a replacement keyboard driver for systems that don't support the legacy keyboard interface, but that requires writing a complete USB driver stack, so don't expect it to happen any time soon.

**Comment by allanlaal** [comment]
@martinwhitaker  is it possible specify a config file that will have pcmemtest do a scan and save badram output to disk?

**Comment by allanlaal** [comment]
my usb keyboard does not work in UEFI mode with CSM enabled

**Comment by martinwhitaker** [comment]
@allanlaal, check if there's a BIOS option to enable USB legacy keyboard support, and if so, make sure it is enabled. But it's possible the BIOS will only turn it on if you boot in legacy mode (I have a new Gigabyte motherboard which does that).

**Comment by allanlaal** [comment]
USB legacy keyboard is also enabled

also tried in BIOS mode
also tried forcing the USB3 ports to USB2
also tried connecting the usb kb directly (not through a USB2 hub)

the usb kb works in all cases in BIOS config, so this seems like a pcmemtest specific issue - maybe its selecting the first detected keyboard?

**Comment by martinwhitaker** [comment]
No, it's a BIOS specific issue. PCMemTest (like MemTest86+ before it) uses port 0x60 to access the keyboard, so relies on the BIOS to set up port 0x60/0x64 emulation. If the keyboard is working in PCMemTest when you boot in legacy mode, your BIOS is doing that for legacy boot but not for UEFI boot. I have one (Gigabyte) motherboard that behaves like that, another two (ASUS) motherboards where the keyboard works for both legacy and UEFI boot.

**Comment by allanlaal** [comment]
to clarify: my external usb keyboard works in BIOS setup/config, but does not work in pcmemtest in either BIOS boot or UEFI boot

its not a critical issue for me, I guess pcmemtest/mb chooses the first keyboard, then 99% users are happy and #5 satisfies the rest of that 1% :)
