### ISSUE TITLE
Pass complete, but its only at 73%?

### ISSUE THREAD

**Issue by colemickens** [martinwhitaker/pcmemtest#20]
Hi! Thank you for pcmemtest. I'm excited to get another piece of non-free software off my machine.

Just an FYI, there's work in NixOS to add an option for users to have a pcmemtest added to our grub: https://github.com/NixOS/nixpkgs/issues/156884

But when I ran it, I was a bit confused by the output. It says "pass complete", but it's not at 100% and it kept going?

![PXL_20220320_214325956](https://user-images.githubusercontent.com/327028/159435874-47519ac2-44bd-495d-a303-cf8fa8572968.jpg)

**Comment by colemickens** [comment]
Is it just that it runs multiple passes within one "test" and I needed to wait until I saw "test complete"? (Of course I just minutes ago found my actual source of ZFS corruption and no longer suspect my memory...)

**Comment by martinwhitaker** [comment]
No, a pass is a run through all the tests. What's probably misleading you is that the number displayed after "Pass:" is a count of the number of completed passes. So, as it is displaying "1", that means that the first pass has completed and it is doing the second pass.

**Comment by colemickens** [comment]
I see. Okay! Thanks again!
