### ISSUE TITLE
will the memory whose address is over 4GB be tested?

### ISSUE THREAD

**Issue by doyanger** [martinwhitaker/pcmemtest#3]
In the setup_vm_map(), mapping between physical and virtual address is setup.
In first_word_mapping(), the higher addresses DRAM are all mapped into the 2GB~3GB range,
I'm confused! how about the address over 4GB?
Thank you!
------------------------------------------------
void *first_word_mapping(uintptr_t page)
{
    void *result;
    if (page < PAGE_C(2,GB)) {
        // If the address is less than 2GB, it is directly mapped.
        result = (void *)(page << PAGE_SHIFT);
    } else {
        // Otherwise it is mapped to the third GB.
        uintptr_t alias = PAGE_C(2,GB) + page % PAGE_C(1,GB);
        result = (void *)(alias << PAGE_SHIFT);
    }
    return result;
}

**Comment by martinwhitaker** [comment]
Yes, the physical memory is divided into 1GB pages, and each page in turn is mapped into the virtual memory address range 2G - 3G. This allows the tests to be run on 32-bit processors with more than 4GB of physical memory. Of course you don't actually need to page the memory like this on a 64-bit processor, but wherever possible I use the same code for both 32-bit and 64-bit.

**Comment by doyanger** [comment]
Hi martinwhitaker
Thank you for your quick reply!
1. With currently mapping schematic, on 64-bit processor, physical address 6.5GB is mapped to virtual address 2.5GB,  physical address 7.5GB is also mapped to the virtual address 2.5GB. how the CPU or Memory Controller can distinguish such 2 physical address? is there any hardware mechanism, inside the modern CPU that I don't know before, to handle such issue.
2. on a 64-bit processor, all the physical address could be directly mapped? just like you do in first_word_mapping() for the first 2GB. or could it be accessed directly by physical address without first_word_mapping()?
Sorry for any inconvenience my questions cause and appreciate your patience!

**Comment by martinwhitaker** [comment]
1. Only one 1GB region of physical memory is mapped into virtual memory at any particular time. The memory test controls the mapping, so knows which region it is.
2. As said before, yes, on a 64-bit processor there is no need to do this mapping. But that would require two branches of the code, one that worked on 32-bit processors, another that worked on 64-bit processors. I don't want to maintain two branches when one can work for both. The remapping is not a big overhead.

**Comment by doyanger** [comment]
Hi martinwhitaker

> 1. Only one 1GB region of physical memory is mapped into virtual memory at any particular time. The memory test controls the mapping, so knows which region it is.

map_window() will do the mapping. thank you!

> on a 64-bit processor there is no need to do this mapping.

Excuse me, maybe it is. I supposed it is not the mapping like in map_window(), but 4 level page approach(PML4 -> PDPT -> PD -> PT) should be set correctly if test on a 64-bit processor and want get a wider test window/region which is larger than 1GB, 4GB or more.  Am I right?

**Comment by martinwhitaker** [comment]
A 4 level page table is used for both 32-bit and 64-bit, to allow more than 4GB of physical memory to be tested (using PAE for 32-bit). See boot/startup32.S and boot/startup64.S.

**Comment by doyanger** [comment]
Hi martinwhitaker 
  thank you!
