### ISSUE TITLE
ADD grub-mkconfig script

### ISSUE THREAD

**Issue by allanlaal** [martinwhitaker/pcmemtest#4]
there's a rpm package of pcmemtest with a functional grub.d grub-mkconfig script

we could port that script from there

**Comment by allanlaal** [comment]
the only change was that update-grub2 needed the image files to contain version numbers:
Found pcmemtest image: /boot/pcmemtest-1.4.efi
Found pcmemtest image: /boot/pcmemtest-1.4.bin

(I renamed the files to pcmemtest, so they would no clash with the original memtest in the future)

**Comment by allanlaal** [comment]
here's the script with some modifications to the menuentry row (to make it more clear) and use `linux` to launch it instead of `linux32` on my 64bit system:

	#! /bin/sh
	set -e

	# grub-mkconfig helper script.
	# Copyright (C) 2011  Michal Ambroz <rebus@seznam.cz>
	#
	# you can redistribute it and/or modify
	# it under the terms of the GNU General Public License as published by
	# the Free Software Foundation, either version 3 of the License, or
	# (at your option) any later version.
	#
	# Distributed in the hope that it will be useful,
	# but WITHOUT ANY WARRANTY; without even the implied warranty of
	# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	# GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License
	# along with the script.  If not, see <http://www.gnu.org/licenses/>.

	prefix=/usr
	exec_prefix=/usr
	bindir=/usr/bin
	grublibdir=/usr/share/grub
	. ${grublibdir}/grub-mkconfig_lib

	export TEXTDOMAIN=grub
	export TEXTDOMAINDIR=${prefix}/share/locale

	CLASS=""

	IMAGE="pcmemtest"

	# loop-AES arranges things so that /dev/loop/X can be our root device, but
	# the initrds that Linux uses don't like that.
	case ${GRUB_DEVICE} in
	  /dev/loop/*|/dev/loop[0-9])
		GRUB_DEVICE=`losetup ${GRUB_DEVICE} | sed -e "s/^[^(]*(\([^)]\+\)).*/\1/"`
	  ;;
	esac

	if [ "x${GRUB_DEVICE_UUID}" = "x" ] || [ "x${GRUB_DISABLE_LINUX_UUID}" = "xtrue" ] \
		|| ! test -e "/dev/disk/by-uuid/${GRUB_DEVICE_UUID}" \
		|| uses_abstraction "${GRUB_DEVICE}" lvm; then
	  LINUX_ROOT_DEVICE=${GRUB_DEVICE}
	else
	  LINUX_ROOT_DEVICE=UUID=${GRUB_DEVICE_UUID}
	fi

	if [ "x`${grub_probe} --device ${GRUB_DEVICE} --target=fs 2>/dev/null || true`" = xbtrfs ]; then
	  rootsubvol="`make_system_path_relative_to_its_root /`"
	  rootsubvol="${rootsubvol#/}"
	  if [ "x${rootsubvol}" != x ]; then
		GRUB_CMDLINE_LINUX="rootflags=subvol=${rootsubvol} ${GRUB_CMDLINE_LINUX}"
	  fi
	fi

	pcmemtest_entry ()
	{
	  os="$1"
	  version="$2"
	  recovery="$3"
	  args="$4"
	  printf "menuentry 'PCMemTest 64bit %s %s' {\n"  "${os}" "${version}" 


	  if [ x$dirname = x/ ]; then
		if [ -z "${prepare_root_cache}" ]; then
		  prepare_root_cache="$(prepare_grub_to_access_device ${GRUB_DEVICE} | sed -e "s/^/\t/")"
		fi
		printf '%s\n' "${prepare_root_cache}"
	  else
		if [ -z "${prepare_boot_cache}" ]; then
		  prepare_boot_cache="$(prepare_grub_to_access_device ${GRUB_DEVICE_BOOT} | sed -e "s/^/\t/")"
		fi
		printf '%s\n' "${prepare_boot_cache}"
	  fi
	  message="$(gettext_printf "Loading %s %s ..." "${os}" "${version}")"
	  cat << EOF
		echo	'$message'
		set	gfxpayload=640x400,800x600,1024x768
		linux	${rel_dirname}/${basename}
	}
	EOF
	}

	case x`uname -m` in
		xi?86 | xx86_64)
		list=`for i in /boot/${IMAGE}* ; do
		              if grub_file_is_not_garbage "$i" ; then echo -n "$i " ; fi
		          done` ;;
		*) 
		list=`for i in /boot/${IMAGE}* ; do
		              if grub_file_is_not_garbage "$i" ; then echo -n "$i " ; fi
			 done` ;;
	esac

	prepare_boot_cache=
	prepare_root_cache=

	while [ "x$list" != "x" ] ; do
	  linux=`version_find_latest $list`
	  echo "Found pcmemtest image: $linux" >&2
	  basename=`basename $linux`
	  dirname=`dirname $linux`
	  rel_dirname=`make_system_path_relative_to_its_root $dirname`
	  version=`echo $basename | sed -e "s,^[^0-9]*-,,g"`
	  alt_version=`echo $version | sed -e "s,\.old$,,g"`
	  linux_root_device_thisversion="${LINUX_ROOT_DEVICE}"


	  pcmemtest_entry "${OS}" "${version}" false \
		  "${GRUB_CMDLINE_LINUX} ${GRUB_CMDLINE_LINUX_DEFAULT}"

	  list=`echo $list | tr ' ' '\n' | grep -vx $linux | tr '\n' ' '`
	done

**Comment by martinwhitaker** [comment]
I assume this comes from the Mageia package, which I maintain. As you have found, this isn't totally  portable, so I'd rather not include it here. Also, adding it would mean I had to make this a multi-licensed project.

**Comment by allanlaal** [comment]
but.. but.. the grub-mkconfig helper script I pasted is also licensed as `GNU General Public License` ?!

**Comment by martinwhitaker** [comment]
GPL v2 != GPL v3

**Comment by martinwhitaker** [comment]
Closing as won't fix.
