### ISSUE TITLE
ADD a secondary `OK` button in addition to `Esc`

### ISSUE THREAD

**Issue by allanlaal** [martinwhitaker/pcmemtest#5]
ADD a secondary `OK` button in addition to `Esc`

use case:
 my usb keyboard does not work in UEFI with compability enabled AND the internal kb is missing the `Esc` key :dagger:

**Comment by martinwhitaker** [comment]
Do you mean:

1. Your keyboard doesn't have an Esc key.
2. Your Esc key is broken.
3. PCMemTest doesn't recognise it (presumably because it is generating a different scan code).

**Comment by allanlaal** [comment]
2.

**Comment by allanlaal** [comment]
I already made the changes, but all Fx keys got shifted by 1 :/

https://github.com/allanlaal/pcmemtest/commit/d3d696b477ba90846e0d3ed036964fed58a1ef00

prolly because the order of elements in`keymap` in `system/keyboard.c` matters?

**Comment by martinwhitaker** [comment]
keymap[] is a lookup table, indexed by the scan code received from the keyboard. Backspace is scan code 0x0e, which currently generates the character '\b' (which is the escape code for backspace). So either define BACKSPACE as '\b' or just use '\b' directly in your code.

**Comment by martinwhitaker** [comment]
Done. I've chosen F10 as the alternative.
