### ISSUE TITLE
ADD save badram results to file #badmem #memtest=

### ISSUE THREAD

**Issue by allanlaal** [martinwhitaker/pcmemtest#6]
use case:

with lots of errors it will take eons to transcribe the bad blocks from photos to the `/etc/default/grub` files `GRUB_BADRAM` option

**Comment by allanlaal** [comment]
ultra-luxury optional feature: fill out the `GRUB_BADRAM` value in `/etc/default/grub` automatically

**Comment by martinwhitaker** [comment]
PCMemTest is a bare-metal application. In legacy mode it can use BIOS interrupt calls, so can do simple reads/writes to fixed sectors on floppy and hard disks. In UEFI mode it doesn't have any way to access disks. In either case, this would require adding a complete file system layer plus device drivers for disks not supported by the BIOS.

If you are getting that many memory errors, it's time to replace your memory!

**Comment by allanlaal** [comment]
yeah, having it write files is beyond wishful thinking :D 
closing
