### ISSUE TITLE
FIX badram report output is empty

### ISSUE THREAD

**Issue by allanlaal** [martinwhitaker/pcmemtest#7]
see screenshot:

![IMG_20210717_152239_907](https://user-images.githubusercontent.com/740826/126038146-d55ffd9d-9730-4d89-bfa3-9361e90c8228.jpg)

the errors count is 13k. I let it run 43mins (found 90k errors) and still got nothing

**Comment by martinwhitaker** [comment]
I've pushed a fix for this. Please check it works for you.
